"""Combine base analysis Markdown with an optional LLM layer and disclaimer."""

from __future__ import annotations

from typing import Optional

_DISCLAIMER = """## Disclaimer

This output is generated by an automated multi-agent research framework for **informational and research purposes only**. It is **not** investment advice, a solicitation, or a recommendation to buy or sell any security. Always do your own due diligence and consult a qualified professional before making financial decisions. See the upstream project and [Tauric Research disclaimer](https://tauric.ai/disclaimer/) for further context."""


def assemble_full_report_markdown(
    *,
    base_markdown: str,
    enhancement_markdown: Optional[str] = None,
    include_disclaimer: bool = True,
) -> str:
    parts = [base_markdown.rstrip()]
    if enhancement_markdown and enhancement_markdown.strip():
        parts.append("\n\n---\n\n## Polished summary (LLM)\n\n")
        parts.append(enhancement_markdown.strip())
    if include_disclaimer:
        parts.append("\n\n---\n\n")
        parts.append(_DISCLAIMER)
    return "\n".join(parts).strip() + "\n"
